name: Auto Update Token RCTI

on:
  schedule:
    # Berjalan otomatis setiap 2 menit
    - cron: '*/2 * * * *'
  workflow_dispatch:
    # Memungkinkan kamu menjalankan script ini secara manual kapan saja dari tab "Actions"

# TAMPILKAN IZIN SECARA EKSPLISIT DI SINI (SOLUSI ERROR 403)
permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Tarik Kode dari GitHub
        uses: actions/checkout@v4

      - name: 🐍 Siapkan Mesin Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install module requests
        run: pip install requests

      - name: 🚀 Jalankan Bot Update Token
        run: python update_rcti.py

      - name: 💾 Simpan (Commit) Perubahan ke GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add streams/id.m3u
          # Cek apakah ada perubahan, jika ada lakukan commit, jika tidak abaikan
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update token RCTI m3u8" && git push)
